runtime: nodejs16

env_variables:
  NODE_ENV: "production"  # Use 'production' for the deployed environment
  DATABASE_URL: "${{secrets.DATABASE_URL}}"

instance_class: F2

handlers:
  - url: /.*  
    script: auto
